// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic structure that will be replaced

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          role: 'admin' | 'member' | 'trainer'
          created_at: string
          updated_at: string
          is_active: boolean
        }
        Insert: {
          id?: string
          email: string
          full_name?: string | null
          phone?: string | null
          role: 'admin' | 'member' | 'trainer'
          created_at?: string
          updated_at?: string
          is_active?: boolean
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone?: string | null
          role?: 'admin' | 'member' | 'trainer'
          created_at?: string
          updated_at?: string
          is_active?: boolean
        }
      }
      members: {
        Row: {
          id: string
          user_id: string
          emergency_contact: string | null
          medical_conditions: string | null
          date_of_birth: string | null
          gender: string | null
          address: string | null
          height: number | null
          weight: number | null
          profile_photo_url: string | null
          joined_at: string
          membership_status: 'active' | 'expired' | 'suspended'
        }
        Insert: {
          id?: string
          user_id: string
          emergency_contact?: string | null
          medical_conditions?: string | null
          date_of_birth?: string | null
          gender?: string | null
          address?: string | null
          height?: number | null
          weight?: number | null
          profile_photo_url?: string | null
          joined_at?: string
          membership_status?: 'active' | 'expired' | 'suspended'
        }
        Update: {
          id?: string
          user_id?: string
          emergency_contact?: string | null
          medical_conditions?: string | null
          date_of_birth?: string | null
          gender?: string | null
          address?: string | null
          height?: number | null
          weight?: number | null
          profile_photo_url?: string | null
          joined_at?: string
          membership_status?: 'active' | 'expired' | 'suspended'
        }
      }
      // More table types will be generated automatically
      [key: string]: any
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'admin' | 'member' | 'trainer'
      membership_status: 'active' | 'expired' | 'suspended'
      session_status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled'
      booking_status: 'confirmed' | 'pending' | 'cancelled' | 'attended'
      package_type: 'monthly' | 'quarterly' | 'yearly' | 'session_based'
      payment_status: 'pending' | 'completed' | 'failed' | 'refunded'
      notification_type: 'booking' | 'payment' | 'reminder' | 'system'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 
